export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <a href="/" className="text-sm text-blue-600 hover:underline mb-8 block">&larr; BSC Tool</a>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: April 2026</p>

        <div className="prose prose-sm text-gray-700 space-y-8">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Service</h2>
            <p>BSC Tool is an online Balanced Scorecard builder provided by Digital Export Manager (Lia Kereselidze). By using the tool, you agree to these terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Free tier</h2>
            <p>The free tier includes:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Full BSC builder (objectives, KPIs, initiatives)</li>
              <li>Strategy map</li>
              <li>Progress tracking</li>
              <li>PDF export</li>
              <li>1 AI-powered BSC generation per scorecard</li>
              <li>Shareable link</li>
            </ul>
            <p className="mt-3">Free tier features may change. We will notify users of significant changes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Paid tier</h2>
            <p>Paid features require a one-time or subscription payment. Prices are shown in GEL. Payments are non-refundable unless the service was not delivered as described. Contact us within 7 days if you believe there is an issue.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Your content</h2>
            <p>You own all content you create in the tool (objectives, KPIs, strategies). We do not claim any rights to your business data. You are responsible for the accuracy of the information you enter.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. AI-generated content</h2>
            <p>Content generated by the AI feature is a starting point and suggestion only. It is not professional strategic consulting advice. You are responsible for reviewing, editing, and using any AI-generated content appropriately for your business.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the tool for illegal purposes</li>
              <li>Attempt to abuse or circumvent usage limits</li>
              <li>Share access credentials with others</li>
              <li>Scrape or automate requests to the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Availability</h2>
            <p>We aim for high availability but do not guarantee uninterrupted service. We are not liable for losses caused by downtime or service interruptions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Limitation of liability</h2>
            <p>The tool is provided &ldquo;as is&rdquo;. Digital Export Manager is not liable for any business decisions made based on content created in or generated by this tool. Our total liability shall not exceed the amount you paid for the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Changes to terms</h2>
            <p>We may update these terms. Continued use of the service after changes means you accept the new terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Contact</h2>
            <p>Questions: <a href="mailto:likunakereselidze@gmail.com" className="text-blue-600">likunakereselidze@gmail.com</a></p>
          </section>

        </div>
      </div>
    </div>
  );
}
